# Xamarin.iOS
# Build a Xamarin.iOS app and Xamarin.UITest assembly.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/xamarin

pool:
  vmImage: 'macOS 10.13'

steps:
- task: XamariniOS@2
  inputs:
    solutionFile: '**/*.sln'
    configuration: 'Release'
    packageApp: false
    buildForSimulator: true
